"""
Auto-Content-Bot: AI-Powered Content Automation System
Main entry point for the CLI pipeline.
"""
from services.gmail_listener import GmailListener
from services.ai_engine import AIEngine
from services.wp_publisher import WordPressPublisher
from services.social_manager import SocialMediaManager
from config import Config


def print_banner():
    """Display startup banner with configuration status."""
    print("\n" + "="*60)
    print("🤖 AUTO-CONTENT-BOT - AI Content Automation System")
    print("="*60)
    
    status = Config.get_status()
    mode = "DEMO MODE" if status['demo_mode'] else "PRODUCTION MODE"
    print(f"Running in: {mode}\n")
    
    print("Integration Status:")
    print(f"  ├── OpenAI:    {'✅ Connected' if status['openai'] else '⚪ Mock Mode'}")
    print(f"  ├── WordPress: {'✅ Connected' if status['wordpress'] else '⚪ Mock Mode'}")
    print(f"  ├── Gmail:     {'✅ Connected' if status['smtp'] else '⚪ Mock Mode'}")
    print(f"  ├── LinkedIn:  {'✅ Connected' if status['linkedin'] else '⚪ Mock Mode'}")
    print(f"  └── Twitter:   {'✅ Connected' if status['twitter'] else '⚪ Mock Mode'}")
    print("="*60 + "\n")


def run_pipeline(custom_email: dict = None):
    """
    Main execution function for the Auto-Content-Bot.
    Orchestrates the flow: Email -> AI -> CMS -> Social Media -> Report.
    
    Args:
        custom_email: Optional custom email data to process (for testing/dashboard)
    
    Returns:
        dict: Pipeline execution results
    """
    print_banner()
    print("🚀 Starting Content Pipeline...\n")

    # 1. INITIALIZATION
    email_service = GmailListener()
    ai_service = AIEngine()
    wp_service = WordPressPublisher()
    social_service = SocialMediaManager()

    # 2. CHECK FOR TASKS (Input)
    email_data = custom_email or email_service.check_new_emails()
    
    if not email_data:
        print("📭 No new tasks found. Exiting.")
        return {"status": "no_tasks", "message": "No new emails to process"}

    print(f"\n📧 Processing: {email_data['subject']}")
    print(f"   From: {email_data['sender']}")
    print("-" * 50)

    # 3. GENERATE CONTENT (Processing)
    content_package = ai_service.generate_content_package(email_data)

    # 4. PUBLISH CONTENT (Output)
    results = {
        "status": "success",
        "email": email_data,
        "generated_content": {},
        "published": {}
    }

    # Step A: Publish to WordPress
    if "blog_post" in content_package:
        blog = content_package["blog_post"]
        draft_link = wp_service.create_draft(blog["title"], blog["content"])
        results["published"]["wordpress"] = {
            "type": "blog_post",
            "title": blog["title"],
            "link": draft_link
        }
        results["generated_content"]["blog_post"] = blog

    if "case_study" in content_package:
        case = content_package["case_study"]
        case_link = wp_service.create_draft(case["title"], case["content"])
        results["published"]["wordpress_case_study"] = {
            "type": "case_study",
            "title": case["title"],
            "link": case_link
        }
        results["generated_content"]["case_study"] = case

    # Step B: Publish to Social Media
    if "social_post" in content_package:
        linkedin_result = social_service.post_to_linkedin(content_package["social_post"])
        results["published"]["linkedin"] = linkedin_result
        results["generated_content"]["social_post"] = content_package["social_post"]

    if "twitter_post" in content_package:
        twitter_result = social_service.post_to_twitter(content_package["twitter_post"])
        results["published"]["twitter"] = twitter_result
        results["generated_content"]["twitter_post"] = content_package["twitter_post"]

    if "product_description" in content_package:
        results["generated_content"]["product_description"] = content_package["product_description"]

    # 5. REPORTING (Feedback Loop)
    wp_link = results["published"].get("wordpress", {}).get("link", "N/A")
    social_platforms = [k for k in results["published"].keys() if k != "wordpress"]
    
    report_message = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✅ TASK COMPLETED SUCCESSFULLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📝 Content Generated:
{chr(10).join(f'   • {k}' for k in content_package.keys())}

📰 WordPress Draft: {wp_link}

📱 Social Media: {', '.join(social_platforms) if social_platforms else 'None'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Auto-Content-Bot 🤖
    """
    
    email_service.send_report(
        to_email=email_data["sender"], 
        subject="✅ Content Generation Complete", 
        body=report_message
    )

    print("\n" + "="*60)
    print("🏁 Pipeline finished successfully!")
    print("="*60)
    
    return results


def demo_mode():
    """Run a quick demo with sample data."""
    print("\n" + "*"*60)
    print("🎮 DEMO MODE - Running with sample data")
    print("*"*60)
    
    sample_email = {
        "id": "demo_001",
        "sender": "demo@example.com",
        "subject": "TASK: Create Marketing Content for Product Launch",
        "body": """Please create the following content for our new product launch:

Product: Smart Home Hub 3000
Price: $199

We need:
- A compelling blog post about smart home technology trends
- LinkedIn post for our company page
- Twitter announcement
- Product description for our website

Target audience: Tech-savvy homeowners aged 30-50
Tone: Professional but approachable

Thank you!""",
        "thread_id": "demo_thread_001"
    }
    
    return run_pipeline(custom_email=sample_email)


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1 and sys.argv[1] == "--demo":
        demo_mode()
    else:
        run_pipeline()
